### ISSUE TITLE
Подписать своим штампом

### ISSUE THREAD

**Issue by Buba5473** [dkxce/Pospisaka#1]
На основе идущего с программой, сделал свой штамп (в аттаче). Только вот информация из ЭП в него не добавляется. Что необходимо модернизировать?
![pah-copah_3_268x268](https://github.com/user-attachments/assets/5dad0427-d0ec-4a19-ad4e-12bb83665a04)

**Comment by dkxce** [comment]
В вашем шаблоне штампа неверные реперные точки. Видимо в процессе обработки съехали цвета.    
![387544661-5dad0427-d0ec-4a19-ad4e-12bb83665a04](https://github.com/user-attachments/assets/33b8684e-3f90-4a13-aa6e-5fc4ae05beb4)    
Если поправить на [нужные](https://github.com/dkxce/Pospisaka/blob/main/podpisaka/bin/Debug/Stamps/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD_%D1%88%D1%82%D0%B0%D0%BC%D0%BF%D0%B0_%D1%81%D0%B5%D1%80%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%B0.md), то все добавляется.   

![Изображение из буфера обмена](https://github.com/user-attachments/assets/bb78360b-2a8b-4098-9b86-52cb9f64dc42)

Правильный шаблон:
![Buba5473](https://github.com/user-attachments/assets/61585c73-d98b-4ee1-b356-dcbc41c1defb)
